apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: ClusterIP
  ports:
    - name: eighty
      port: 80
      targetPort: 80
  selector:
    app: {{.Values.service.name}}